WeGoMigration/Controllers/AppUsersController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using WeGoMigration.Entities;
using WeGoMigration.IServices;
using WeGoMigration.Models;
using static WeGoMigration.Entities.Common;
namespace WeGoMigration.Controllers
{
    public class AppUsersController : Controller
    {
        IAppUsers _IAppUsers;
        IAppUserPosts _appUserPosts;
        private readonly IHttpContextAccessor _httpContextAccessor;
        public AppUsersController(IAppUsers IAppUsers, IAppUserPosts appUserPosts, IHttpContextAccessor httpContextAccessor)
        {
            _IAppUsers = IAppUsers;
            _appUserPosts = appUserPosts;
            _httpContextAccessor = httpContextAccessor;
        }
        public IActionResult Index(string Message)
        {
            ViewBag.Message = Message;
            return View();
        }
        public IActionResult Register()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Register(Register register)
        {
            try
            {
                string decrptypass = EnryptString(register.Password);
                if (ModelState.IsValid)
                {
                    var appUsers = new AppUser
                    {
                        FullName = register.FullName,
                        UserName = register.UserName,
                        Email = register.Email,
                        ReffralCode = register.ReffralCode,
                        Password = decrptypass,
                        RepaetPassword = decrptypass,
                        PhoneNumber = register.PhoneNumber,
                        IsWeb = true,
                        IsAndroid = false,
                        IsIos = false,
                        IsActive = true,
                        CreatedBy = 1,
                        CreatedOn = DateTime.Now,
                        UpdatedBy = 1,
                        UpdatedOn = DateTime.Now,
                        LastLogin = DateTime.Now,
                        RoleId =1,
                    };
                    _IAppUsers.RegisterUser(appUsers);
                    return RedirectToAction("Index", new { Message = "You have registered succesfully!!" });
                }
                return View();
            }
            catch (Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View();
            }
        }
        public IActionResult getUserPosts(int UserId)
        {
            List<GetUserPosts> userPosts = _appUserPosts.GetUserPostsById(UserId);
            List<PostComments> PostComments = _appUserPosts.GetCommentsList(UserId);
            List<GetUserPosts> userPostsNew = new List<GetUserPosts>();
            foreach (var item in userPosts)
            {
                userPostsNew.Add(new GetUserPosts
                {
                    PostText = item.PostText,
                    Picture = item.Picture,
                    PostId = item.PostId,
                    CommentText = item.CommentText,
                    CommentId = item.CommentId,
                    postComments = PostComments.Where(x => x.PostId == item.PostId).ToList()
                }); 
            }
            ViewBag.UserPostById = userPostsNew;
            ViewBag.UserPostDetails = userPostsNew.ToList();
            return PartialView("_loadAllPost");
        }
        public IActionResult Login(LoginVm loginVm)
        {
            string message = "";
            List<Login> loginresult = new List<Login>();
            try
            {
                if (ModelState.IsValid)
                {
                    //string plaintext = DecryptString("d2V5b3Vnb0AxMjM=");
                    string EncrptedPassword = EnryptString(loginVm.Password);
                    var loginModel = new LoginModel
                    {
                        UserName = loginVm.UserName,
                        Password = EncrptedPassword
                    };
                    loginresult = _IAppUsers.UserLogin(loginModel);
                }
                var lgnResult = loginresult.Where(p => p.AppUserId != 0).SingleOrDefault();
                

                if (lgnResult != null && lgnResult.RoleId ==1)
                {
                    HttpContext.Session.SetInt32("SessionUserId", lgnResult.AppUserId);
                    HttpContext.Session.SetString("Username", lgnResult.FullName);
                    if (lgnResult.AppUserId == 0)
                    {
                        ViewBag.Message = "Email or password is wrong please try again";
                        return RedirectToAction("Index");
                    }
                    getUserPosts(lgnResult.AppUserId);
                    ViewBag.ProfileDetails = lgnResult;
                    return View();
                }
                if (lgnResult != null && lgnResult.RoleId == 2)
                {
                    HttpContext.Session.SetInt32("SessionUserId", lgnResult.AppUserId);
                    if (lgnResult.AppUserId == 0)
                    {
                         message = "Email or password is wrong please try again";
                        return RedirectToAction("Index", new { Message = message });
                    }
                    ViewBag.ProfileDetails = lgnResult;
                    return RedirectToAction("Index", "Admin");
                }
                 message = "Email or password is wrong please try again";
                return RedirectToAction("Index", new { Message = message });
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return RedirectToAction("Index");
            }
        }
        public IActionResult CreatePost()
        {
            return PartialView("_CreatePost");
        }
        [HttpGet]
        public IActionResult GetAbout(int UserId)
        {
            var about = _appUserPosts.GetAboutByUser(UserId);
            return PartialView("_AboutPartialView", about);
        }
        [HttpPost]
        public JsonResult SavePost(string posttexts, IFormFile file,int PostId)
        {
            if (!string.IsNullOrEmpty(posttexts) || file.Length > 0)
            {
                var post = new Post();
                post.PostText = posttexts;
                post.CreatedBy = Convert.ToInt32(HttpContext.Session.GetInt32("SessionUserId"));
                post.PostId = PostId;
                if (file != null)
                {
                    using (MemoryStream stream = new MemoryStream())
                    {
                        file.CopyTo(stream);
                        var fileBytes = stream.ToArray();
                        post.ImageDataFiles = fileBytes;
                    }
                }
                _appUserPosts.SavePosts(post);
            }
            return Json("");
        }

        public IActionResult getUserPostsByPostId(int PostId)
        {
            var post =  _appUserPosts.GetUserPostsByPostId(PostId);
            var modal = new WeGoMigration.Entities.Common.PostVm()
            {
                PostText = post.PostText,
                Picture = post.Picture

            };
            return PartialView("_CreatePost", modal);
        }
        public int DeletePostsByPostId(int PostId)
        {
            var post = _appUserPosts.DeletePostsByPostId(PostId);
            return post;
        }

        public IActionResult About(int UserId)
        {
            var about = _appUserPosts.GetAboutByUser(UserId);
            return View(about);
        }

        public int SaveAbout(About about)
        {
            if (about.ImageFile != null)
            {
                using (MemoryStream stream = new MemoryStream())
                {
                    about.ImageFile.CopyTo(stream);
                    var fileBytes = stream.ToArray();
                    about.ImageDataFiles = fileBytes;
                }
            }
            about.UserId = Convert.ToInt32(HttpContext.Session.GetInt32("SessionUserId"));
            var post = _appUserPosts.SaveAboutDetail(about);
            return 1;
        }

        public int PostLikes()
        {
            var post = _appUserPosts.SaveAboutDetail(new About());
            return 1;
        }


        public int SaveUpdateComment(int postId, string commentValue,int commentId, int UserId)
        {
            var post = _appUserPosts.SaveUpdateCommentByPostId(postId, commentValue, UserId, commentId);
            return 1;
        }
        public int DeleteComment(int commentId)
        {
            var post = _appUserPosts.DeleteCommentByCommentId(commentId);
            return 1;
        }
        public int DeleteCommentByPostId(int postId)
        {
            var post = _appUserPosts.DeleteCommentByPostId(postId);
            return 1;
        }

        public IActionResult PostJob()
        {
            return View();
        }
        public IActionResult ForgetPassword()
        {
            ViewBag.NotValidEmail = false;
            return View();
        }

        [HttpPost]
        public ActionResult ForgetPassword(string email)
        {
            if (ModelState.IsValid)
            {
                var appUser = _IAppUsers.GetUserDetails(email)
;
                if (appUser != null && !string.IsNullOrEmpty(appUser.Email))
                {
                    _IAppUsers.RecoverPassword(appUser.Email, appUser.AppUserId);
                    return RedirectToAction("Index");
                }
            }
            ViewBag.NotValidEmail = true;
            return View();
        }
        public IActionResult ResetPassword()
        {
            string ciphertext = _httpContextAccessor.HttpContext.Request.Query["id"];

WeGoMigration/Views/Shared/_About.cshtml
@model WeGoMigration.Entities.About
@{
    ViewData["Title"] = "Login";
}
<link rel="stylesheet" href="https://code.jquery.com/ui/1.13.0/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/ui/1.13.0/jquery-ui.js"></script>
<script src="https://code.jquery.com/jquery-3.6.0.js"></script>
<link rel="stylesheet" href="~/css/Login.css" />
@using (Html.BeginForm())
{
    @await Html.PartialAsync("_headerPart")
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="container">
        <div class="row">
            <div class="col-sm-4 col-md-6">
                @Html.LabelFor(x => x.Name, new { @class = "control-label col-md-2" })
                <div class="col-md-12">
                    @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Name, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-md-6 col-sm-4">
                <div class="form-group">
                    <label asp-for="DateOfBirth" class="control-label"></label>
                    @*<input type="text" id="datepicker">*@
                    <input asp-for="DateOfBirth" id="datepicker" type="text" class="form-control" value="" />
                    <span asp-validation-for="DateOfBirth" class="text-danger"></span>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4 col-md-6">
                @Html.LabelFor(x => x.SkillSet, new { @class = "control-label col-md-2" })
                <div class="col-md-12">
                    @Html.TextBoxFor(x => x.SkillSet, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.SkillSet, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-md-6 col-sm-4">
                @Html.LabelFor(x => x.Education, new { @class = "control-label col-md-2" })
                <div class="col-md-12">
                    @Html.TextBoxFor(x => x.Education, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Education, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4 col-md-6">
                @Html.LabelFor(x => x.Address, new { @class = "control-label col-md-2" })
                <div class="col-md-12">
                    @Html.TextBoxFor(x => x.Address, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Address, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-md-6 col-sm-4">
                @Html.LabelFor(x => x.SpecialAboutYou, new { @class = "control-label col-md-2" })
                <div class="col-md-12">
                    @Html.TextAreaFor(x => x.SpecialAboutYou, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.SpecialAboutYou, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-sm-4">
                @Html.LabelFor(x => x.Career, new { @class = "control-label col-md-2" })
                <div class="col-md-12">
                    @Html.TextBoxFor(x => x.Career, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Career, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <button type="button" class="btn btn-success">Save</button>
    </div>
}
@section scripts {
    <script>
        var js = jQuery.noConflict()
        js(document).ready(function () {
            $("#datepicker").datepicker({
                changeMonth: true,
                changeYear: true
            });
        });

        js("#headerpart").hide();
        js("#navclass").hide()
    </script>
}

WeGoMigration/Views/Shared/_CreatePost.cshtml
@model WeGoMigration.Entities.Common.PostVm
<div class="card-body">
    @using (Html.BeginForm("SavePost", "AppUsers", FormMethod.Post, new { enctype = "multipart/form-data", @id = "createpostform" }))
    {
        <div class="form-horizontal">
            <div class="row">
                <div class="col-md-10">
                    <div class="form-group">
                        @Html.TextBoxFor(model => model.ImageFile, "", new { type = "file", @id = "postimage" }) <br />
                        <img id="ItemPreview" src="">
                    </div>
                    <div class="form-group">
                        @Html.TextAreaFor(model => model.PostText, new { @class = "ckeditor", placeholder = "Content", @id = "posttext", @name = "ptetxt" })
                    </div>
                    <div class="form-group">
                        <input id="submitpost" type="button" value="Post" class="btn btn-primary" />
                        <input type="button" onClick="window.location.reload();" value="Discard" class="btn btn-danger" />
                    </div>
                </div>
            </div>
            
        </div>
    }
</div>




@*<script src="https://code.jquery.com/jquery-1.9.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.0.2/js/toastr.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" />*@
<script src="~/ckeditor/ckeditor.js"></script>
<script src="~/ckeditor/adapters/jquery.js"></script>
<script type="text/javascript">

   

    $("#submitpost").on('click', function () {
        var ck_ed = CKEDITOR.instances.posttext.getData();
        //var myform = document.getElementById("createpostform");
        //var fd = new FormData(myform);
        /* new FormData(document.forms[0])*/
        var formData = new FormData();
        var file = document.getElementById("postimage").files[0];
        debugger
        if (file != null) {
            formData.append("file", file);
            formData.append("posttexts", ck_ed);
            formData.append("PostId", $("#hdnpostId").val())
            $.ajax({
                url: ("/AppUsers/SavePost"),
                type: "POST",
                // dataType: 'json',
                data: formData,
                contentType: false,
                processData: false,
                mimeType: 'multipart/form-data',
                success: function (response) {
                    window.location.reload();
                },
                error: function (er) {
                    alert(er);
                }
            });
        }
        else {
            formData.append("posttexts", ck_ed);
            formData.append("PostId", $("#hdnpostId").val())
            $.ajax({
                url: ("/AppUsers/SavePost"),
                type: "POST",
                // dataType: 'json',
                data: formData,
                contentType: false,
                processData: false,
                mimeType: 'multipart/form-data',
                success: function (response) {
                    window.location.reload();
                },
                error: function (er) {
                    alert(er);
                }
            });
        }
    });
    function fileCheck(obj) {
        var fileExtension = ['jpeg', 'jpg', 'png'];
        if ($.inArray($(obj).val().split('.').pop().toLowerCase(), fileExtension) == -1) {
            alert("Only '.jpeg','.jpg', '.png' formats are allowed.");
        }
    }
</script>

WeGoMigration/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WeGoMigration</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @*<link rel="stylesheet" href="~/css/site.css" />*@
</head>
<body>
    @*<header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WeGoMigration</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>*@
    <div class="container">
        <main role="main" class="pb-3 main">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-center">
        <div class="container">
            <strong> &copy; 2021 - WeGoMigration - <a class="pv" asp-area="" asp-controller="Home" asp-action="PrivacyPolicy">Privacy</a> </strong>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WeGoMigration/Views/Shared/_RecentPostByothers.cshtml
<div class="d-none d-xl-block col-xl-3 right-wrapper">
    <div class="row">
        <div class="col-md-12 grid-margin">
            <div class="card rounded shadow-sm">
                <div class="card-body">
                    <h6 class="card-title">Recent Post By others</h6>
                </div>
            </div>
        </div>
    </div>
</div>